config/routes.rb
BJWlab8::Application.routes.draw do
  resources :games
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :friends, :only => [:new, :create, :destroy]
  resources :collections, :only => [:new, :create, :destroy]

  root :to => 'pages#home'
  match '/home', :to => 'pages#home'
  match '/controlpanel', :to => 'pages#cpanel'
  match '/search', :to => 'pages#gamesearch'
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/collections', :to => 'pages#collections'
  match '/friends', :to => 'pages#friends'
  match '/gpage', :to => 'pages#gpage'
  
  

end

app/models/user.rb
require 'digest'
class User < ActiveRecord::Base
  attr_accessible :password, :password_confirmation, :email
  
  email_regexp = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :password, :presence     => true,
                       :confirmation => true,
                       :length       => {:within => 5..40}
  
  validates :email, :presence   => true,
                    :format     => {:with => email_regexp},
                    :uniqueness => {:case_sensitive => false}
                                      
  before_save :encrypt_password
  
  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end
  
  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil  if user.nil?
    return user if user.has_password?(submitted_password)
  end
  
  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end
  
  private
  
    def encrypt_password
      self.salt = make_salt if new_record?
      self.encrypted_password = encrypt(password)
    end
    
    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end
    
    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end
    
    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController  
  # GET /users
  # GET /users.json
  def index
    if params[:remove].nil?
      @users = User.all
      @title = "User List"
  
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @users }
      end
    else
      @users = User.all
      @title = "User List"
      @user = User.find(params[:remove])
      @friends = Friends.find(:all, :conditions => {:friend_id => @user.id})
      if @friends.any?
        @friends.each do |friend|
          friend.destroy
        end
      end
      @friends = Friends.find(:all, :conditions => {:user_id => @user.id})
      if @friends.any?
        @friends.each do |friend|
          friend.destroy
        end
      end
      @ratings = Ratings.find(:all, :conditions => {:user_id => @user.id})
      if @ratings.any?
        @ratings.each do |rating|
          rating.destroy
        end
      end
      @collections = Collections.find(:all, :conditions => {:user_id => @user.id})
      if @collections.any?
        @collections.each do |coll|
          coll.destroy
        end
      end
      @user.destroy
      redirect_to users_path
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    if !current_user.nil? && @user.email == current_user.email
      @title = "#{current_user.email} - Control Panel"
      redirect_to "/controlpanel"
    else
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @user }
      end
    end

    #respond_to do |format|
    #  format.html # show.html.erb
    #  format.json { render json: @user }
    #end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new
    @title = "User Registration";

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    redirect_to root_path
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome!"
      redirect_to "/controlpanel"
    else
      @title = "Signup"
      render 'new'
    end
  end
#    respond_to do |format|
 #     if @user.save
  #      format.html { redirect_to @user, notice: 'User was successfully created.' }
   #     format.json { render json: @user, status: :created, location: @user }
    #  else
     #   format.html { render action: "new" }
      #  format.json { render json: @user.errors, status: :unprocessable_entity }
       #end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> occured:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
<% @users.each do |user| %>
  <tr>
    <td><%= user.email unless user.admin %></td>
    <td><%= link_to 'Show', user unless user.admin %></td>
    <% if !current_user.nil? %>
      <% if current_user.admin %>
        <td><%= link_to 'Destroy', users_path(:remove => user.id) unless user.admin %></td>
      <% end %>
    <% end %>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div id="signup">
<center>
<%= render 'form' %>

<%= link_to 'Back', users_path %>
</center>
</div>

app/views/users/show.html.erb
<center>
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<table>
	<%
		@check = false
		@friends = Friends.find(:all, :conditions => {:user_id => @user.id})
		#['user_id LIKE ?', @user.id])
		if @friends.any?
			@friends.each do |friend|
				if !current_user.nil? && friend.friend_id == current_user.id
					@check = true
				end
			end
		end
	%>
	<% if @user.view || @check %>
		<% @coll = Collections.find(:all, :conditions => {:user_id => @user.id})
		#['user_id LIKE ?', @user.id]) %>
		<% if @coll.any? %>
		<% @coll.sort! { |a,b| a.name.downcase <=> b.name.downcase } %>
		  <% @coll.each do |game| %>
		  <% @game = Game.find_by_id(game.game_id) %>
		  <tr>
		  	<td width="300"><%= link_to @game.name, gpage_path(:param1 => @game) %></td>
		  </tr>
		  <% end %>
		<% end %>
	<% else %>
		<p><font color="red">This user has his/her collection set to private.</font></p>
	<% end %>
</table>
<%= link_to 'Back', users_path %>
</center>