config/routes.rb
BJWlab8::Application.routes.draw do
  resources :games
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :friends, :only => [:new, :create, :destroy]
  resources :collections, :only => [:new, :create, :destroy]

  root :to => 'pages#home'
  match '/home', :to => 'pages#home'
  match '/controlpanel', :to => 'pages#cpanel'
  match '/search', :to => 'pages#gamesearch'
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/collections', :to => 'pages#collections'
  match '/friends', :to => 'pages#friends'
  match '/gpage', :to => 'pages#gpage'
  
  

end

app/views/pages/collections.html.erb
<div id="cp-sidebar">
	<%= link_to "Profile", 'controlpanel' %><br/>
	<%= link_to "Friends", 'friends' %><br/>
	<%= link_to "Collections", 'collections' %>
</div>
<div id="cp-user-info">
	<% @coll = Collections.find(:all, :conditions => {:user_id => current_user.id})
	#['user_id LIKE ?', current_user.id]) %>
	<% if @coll.any? %>
	<% @coll.sort! { |a,b| a.name.downcase <=> b.name.downcase } %>
	  <center>
	  <table>
	  <% @coll.each do |game| %>
	  <% @game = Game.find(game.game_id) %>
	  <tr>
	  	<td width="300"><%= link_to @game.name, gpage_path(:param1 => @game) %></td>
	  	<td><%= link_to "Remove", collections_path(:remove => @game.id) %></td>
	  </tr>
	  <% end %>
	  </table>
	  </center>
	<% end %>	
</div>

app/views/pages/cpanel.html.erb
<div id="cp-sidebar">
	<%= link_to "Profile", 'controlpanel' %><br/>
	<%= link_to "Friends", 'friends' %><br/>
	<%= link_to "Collections", 'collections' %>
</div>
<div id="cp-user-info">
	<center>
	<table>
		<tr>
			<th colspan="2">User Profile</th>
		</tr>
		<tr>
			<td>Username:</td>
			<td><%= current_user.email %></td>
		</tr>
	</table>
	<% if !current_user.nil? && current_user.admin %>
	<%= link_to "User List", "/users" %><br/>
	<%= link_to "Game List", "/games" %><br/>
	<%= link_to "Add Game", "/games/new" %><br/>
	<% end %>
	<br/>
	<% if current_user.view %>
		<%= form_tag(controlpanel_path, :method => "get") do %>
	      	<%= hidden_field_tag :priv, "1"  %>
	     	<%= submit_tag("Make Collection Private") %>
	    <% end %>
	<% else %>
		<%= form_tag(controlpanel_path, :method => "get") do %>
	      	<%= hidden_field_tag :pub, "1"  %>
	     	<%= submit_tag("Make Collection Public") %>
	    <% end %>
	<% end %>
	</center>
</div>

app/views/pages/friends.html.erb
<div id="cp-sidebar">
	<%= link_to "Profile", 'controlpanel' %><br/>
	<%= link_to "Friends", 'friends' %><br/>
	<%= link_to "Collections", 'collections' %>
</div>
<div id="cp-user-info">
	<center><br/>
    <%= form_tag(friends_path, :method => "get") do %>
      <%= text_field_tag(:param1) %>
      <%= submit_tag("Add Friend") %>
    <% end %>
    <font color="red"><%= @notice %></font><br/>
    <table>
    <% @friends = Friends.find(:all, :conditions => {:user_id => current_user.id})
    #['user_id LIKE ?', current_user.id]) %>
    <% @friends.each do |friend| %>
    <% @use = User.find_by_id(friend.friend_id) %>
    	<tr>
    	<td width="300"><%= link_to @use.email, @use %></td>
    	<td><%= link_to "Remove", friends_path(:remove => @use.id) %></td>
    	</tr>
    <% end %>
    </table>
	</center>
</div>

app/views/pages/gamesearch.html.erb
<table>
	<% 
	   search_condition = "%" + params[:q] + "%"
	   #MUST USE LIKE INSTEAD OF ILIKE FOR LOCAL CHECKS
       @games = Game.find(:all, :conditions => ['name ILIKE ?', search_condition])
    %>
    <% if @games.any? %>
       <% @games.sort! { |a,b| a.name.downcase <=> b.name.downcase } %>
	    <% @games.each do |game| %>
	    <tr>
			<td><%= link_to "#{game.name}", gpage_path(:param1 => game) %></td>
			<td>
				<% if !current_user.nil? %>
				  <% @check = Collections.find(:all, :conditions => {:user_id => current_user.id, :name => game.name}) %>
				  <% if @check.empty? %>
				    <%= link_to "Add", collections_path(:param1 => game, :q => params[:q]), :post => true %>
				  <% end %>
				<% end %>
			</td>
		</tr>
		<% end %>
	<% else %>
		<%= @notice = "No Matches Found." %>
	<% end %>
</table>

app/views/pages/gpage.html.erb
<div id="game-info">
	<% if !params[:param1].nil?
	     @game = Game.find(params[:param1])
	   end
	%>
	<div class="game-page-title"><%= if !@game.nil?
		                               @pic = @game.image
		                               @desc = @game.description
		                               @rating = @game.rating
		                               @game.name
		                             else
		                               @pic = "none.jpg"
		                               @desc = "No description available."
		                               @rating = ""
		                               "Game Title Here"	
		                             end 
		                         %></div>
	<%= image_tag(@pic, :alt => "No Image", :class => "game-page-image") %>
	<div class="game-page-description"><%= @desc %></div>
	<div class="game-page-rating"><%= sprintf( "%0.01f", @rating ) %> <%= if !@game.nil?
		 										     "/ 10"
		 										     end %></div>
	<div class="game-page-user-rating">
		<% if !current_user.nil? && !@game.nil? %>
			<%
			  @ratings = Ratings.find(:all, :conditions => {:user_id => current_user.id, :game_id => @game.id})
			  if @ratings.any?
			%>
			  <br/><%= " Your rating!" %><br/>
			  <%= @ratings[0].rating %> <%= "/ 10" %>
			<% else%>
			  <%= form_tag(gpage_path, :method => "get") do %>
      			<%= text_field_tag(:param2) %>
      			<%= hidden_field_tag :game, @game.id  %>
     			<%= submit_tag("Rate!") %>
    		  <% end %>
			<% end %>
			<font size="3" color="red"><%= @notice %></font>
		<% end %>
	</div>
</div>

app/views/pages/home.html.erb
<%
  @newest = Game.all
  @rated = Game.all
  @rated.sort! { |a,b| b.rating <=> a.rating }
  @rated1 = @rated[0]
  @rated2 = @rated[1]
  @rated3 = @rated[2]
  @rated4 = @rated[3]
  @rated5 = @rated[4]
  @newest.sort! { |a,b| b.release <=> a.release}
  @count = 0
  @current = Time.now.strftime("%Y/%m/%d")
  while @newest[@count].release > @current
  	@count = @count + 1
  end
  @upcount = @count
  @newest1 = @newest[@upcount]
  @upcount = @upcount + 1
  @newest2 = @newest[@upcount]
  @upcount = @upcount + 1
  @newest3 = @newest[@upcount]
  @upcount = @upcount + 1
  @newest4 = @newest[@upcount]
  @upcount = @upcount + 1
  @newest5 = @newest[@upcount]
  @count = @count - 1
  @coming1 = @newest[@count]
  @count = @count - 1
  @coming2 = @newest[@count]
  @count = @count - 1
  @coming3 = @newest[@count]
  @count = @count - 1
  @coming4 = @newest[@count]
  @count = @count - 1
  @coming5 = @newest[@count]
%>
<div id="main-top"> Just Out!
   <div id="main-top-first" class="main-details"><%= link_to @newest1.name, gpage_path(:param1 => @newest1) %>
   <%= link_to image_tag(@newest1.image, :alt => "no image", :class => "main-image"), gpage_path(:param1 => @newest1) %>
      <div class="main-rating"><span class="rating-font" ><%= sprintf( "%0.01f", @newest1.rating ) %></span>/10</div>
   </div>
   <div id="main-top-second" class="main-details"><%= link_to @newest2.name, gpage_path(:param1 => @newest2) %>
   <%= link_to image_tag(@newest2.image, :alt => "no image", :class => "main-image"), gpage_path(:param1 => @newest2) %>
      <div class="main-rating"><span class="rating-font" ><%= sprintf( "%0.01f", @newest2.rating ) %></span>/10</div>
   </div>
   <div id="main-top-third" class="main-details"><%= link_to @newest3.name, gpage_path(:param1 => @newest3) %>
   <%= link_to image_tag(@newest3.image, :alt => "no image", :class => "main-image"), gpage_path(:param1 => @newest3) %>
      <div class="main-rating"><span class="rating-font" ><%= sprintf( "%0.01f", @newest3.rating ) %></span>/10</div>
   </div>
   <div id="main-top-fourth" class="main-details"><%= link_to @newest4.name, gpage_path(:param1 => @newest4) %>
   <%= link_to image_tag(@newest4.image, :alt => "no image", :class => "main-image"), gpage_path(:param1 => @newest4) %>
      <div class="main-rating"><span class="rating-font" ><%= sprintf( "%0.01f", @newest4.rating ) %></span>/10</div>
   </div>
   <div id="main-top-fifth" class="main-details"><%= link_to @newest5.name, gpage_path(:param1 => @newest5) %>
   <%= link_to image_tag(@newest5.image, :alt => "no image", :class => "main-image"), gpage_path(:param1 => @newest5) %>
      <div class="main-rating"><span class="rating-font" ><%= sprintf( "%0.01f", @newest5.rating ) %></span>/10</div>
   </div>
</div>
<div id="main-bot"> Upcoming Releases!
   <div id="main-bot-first" class="main-details"><%= link_to @coming1.name, gpage_path(:param1 => @coming1) %>
   <%= link_to image_tag(@coming1.image, :alt => "no image", :class => "main-image"), gpage_path(:param1 => @coming1) %>
      <div class="main-rating"><%= @coming1.release %></div>
   </div>
   <div id="main-bot-second" class="main-details"><%= link_to @coming2.name, gpage_path(:param1 => @coming2) %>
   <%= link_to image_tag(@coming2.image, :alt => "no image", :class => "main-image"), gpage_path(:param1 => @coming2) %>
      <div class="main-rating"><%= @coming2.release %></div>
   </div>
   <div id="main-bot-third" class="main-details"><%= link_to @coming3.name, gpage_path(:param1 => @coming3) %>
   <%= link_to image_tag(@coming3.image, :alt => "no image", :class => "main-image"), gpage_path(:param1 => @coming3) %>
      <div class="main-rating"><%= @coming3.release %></div>
   </div>
   <div id="main-bot-fourth" class="main-details"><%= link_to @coming4.name, gpage_path(:param1 => @coming4) %>
   <%= link_to image_tag(@coming4.image, :alt => "no image", :class => "main-image"), gpage_path(:param1 => @coming4) %>
      <div class="main-rating"><%= @coming4.release %></div>
   </div>
   <div id="main-bot-fifth" class="main-details"><%= link_to @coming5.name, gpage_path(:param1 => @coming5) %>
   <%= link_to image_tag(@coming5.image, :alt => "no image", :class => "main-image"), gpage_path(:param1 => @coming5) %>
      <div class="main-rating"><%= @coming5.release %></div>
   </div>
</div>
<div id="sidebar">Top Rated!
   <div id="side-first" class="sidebar-details">
   <%= link_to image_tag(@rated1.image, :alt => "no image", :class => "sidebar-image"), gpage_path(:param1 => @rated1) %>
      <div class="sidebar-rating"><span class="rating-font" ><%= sprintf( "%0.01f", @rated1.rating ) %></span>/10</div>
      <div class="sidebar-name">&nbsp;<%= link_to @rated1.name, gpage_path(:param1 => @rated1) %></div>
   </div>
   <div id="side-second" class="sidebar-details">
   <%= link_to image_tag(@rated2.image, :alt => "no image", :class => "sidebar-image"), gpage_path(:param1 => @rated2) %>
      <div class="sidebar-rating"><span class="rating-font" ><%= sprintf( "%0.01f", @rated2.rating ) %></span>/10</div>
      <div class="sidebar-name"><%= link_to @rated2.name, gpage_path(:param1 => @rated2) %></div>
   </div>
   <div id="side-third" class="sidebar-details">
   <%= link_to image_tag(@rated3.image, :alt => "no image", :class => "sidebar-image"), gpage_path(:param1 => @rated3) %>
      <div class="sidebar-rating"><span class="rating-font" ><%= sprintf( "%0.01f", @rated3.rating ) %></span>/10</div>
      <div class="sidebar-name"><%= link_to @rated3.name, gpage_path(:param1 => @rated3) %></div>
   </div>
   <div id="side-fourth" class="sidebar-details">
   <%= link_to image_tag(@rated4.image, :alt => "no image", :class => "sidebar-image"), gpage_path(:param1 => @rated4) %>
      <div class="sidebar-rating"><span class="rating-font" ><%= sprintf( "%0.01f", @rated4.rating ) %></span>/10</div>
      <div class="sidebar-name"><%= link_to @rated4.name, gpage_path(:param1 => @rated4) %></div>
   </div>
   <div id="side-fifth" class="sidebar-details">
   <%= link_to image_tag(@rated5.image, :alt => "no image", :class => "sidebar-image"), gpage_path(:param1 => @rated5) %>
      <div class="sidebar-rating"><span class="rating-font" ><%= sprintf( "%0.01f", @rated5.rating ) %></span>/10</div>
      <div class="sidebar-name"><%= link_to @rated5.name, gpage_path(:param1 => @rated5) %></div>
   </div>
</div>

app/views/pages/signup.html.erb
<div id="signup">
	<center>
	<br/>
	Register<br/><br/>
	</center>
</div>