config/routes.rb
BJWlab8::Application.routes.draw do
  resources :games
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :friends, :only => [:new, :create, :destroy]
  resources :collections, :only => [:new, :create, :destroy]

  root :to => 'pages#home'
  match '/home', :to => 'pages#home'
  match '/controlpanel', :to => 'pages#cpanel'
  match '/search', :to => 'pages#gamesearch'
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/collections', :to => 'pages#collections'
  match '/friends', :to => 'pages#friends'
  match '/gpage', :to => 'pages#gpage'
  
  

end

app/models/game.rb
class Game < ActiveRecord::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  # GET /games
  # GET /games.json
  def index
    if !current_user.nil? && current_user.admin
      if params[:remove].nil?
        @games = Game.all
        @title = "Games Database"
  
        respond_to do |format|
          format.html # index.html.erb
          format.json { render json: @games }
        end
      else
        @games = Game.all
        @title = "Games Database"
        @rem = Game.find(params[:remove])
        @collections = Collections.find(:all, :conditions => {:game_id => @rem.id})
        if @collections.any?
          @collections.each do |coll|
            coll.destroy
          end
        end
        @ratings = Ratings.find(:all, :conditions => {:game_id => @rem.id})
        if @ratings.any?
          @ratings.each do |rating|
            rating.destroy
          end
        end
        @rem.destroy
        redirect_to games_path
      end
    else
      redirect_to root_path
    end
  end

  # GET /games/1
  # GET /games/1.json
  def show
    if !current_user.nil? && current_user.admin
      @game = Game.find(params[:id])
      @title = "Game Information - #{@game.name}"

      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @game }
      end
    else
      redirect_to root_path
    end
  end

  # GET /games/new
  # GET /games/new.json
  def new
    if !current_user.nil? && current_user.admin
      @game = Game.new
      @title = "Add Game To Database"

      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @game }
      end
    else
      redirect_to root_path
    end
  end

  # GET /games/1/edit
  def edit
    if !current_user.nil? && current_user.admin
      @game = Game.find(params[:id])
    else
      redirect_to root_path
    end
  end

  # POST /games
  # POST /games.json
  def create
    if !current_user.nil? && current_user.admin
      @game = Game.new(params[:game])

      respond_to do |format|
        if @game.save
          format.html { redirect_to @game, notice: 'Game was successfully created.' }
          format.json { render json: @game, status: :created, location: @game }
        else
          format.html { render action: "new" }
          format.json { render json: @game.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to root_path
    end      
  end

  # PUT /games/1
  # PUT /games/1.json
  def update
    if !current_user.nil? && current_user.admin
      @game = Game.find(params[:id])

      respond_to do |format|
        if @game.update_attributes(params[:game])
          format.html { redirect_to @game, notice: 'Game was successfully updated.' }
          format.json { head :ok }
        else
          format.html { render action: "edit" }
          format.json { render json: @game.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to root_path
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    if !current_user.nil? && current_user.admin
      @game = Game.find(params[:id])
      @collections = Collections.find(:all, :conditions => {:game_id => @game.id})
      if @collections.any?
        @collections.each do |coll|
          coll.destroy
        end
      end
      @game.destroy
      respond_to do |format|
        format.html { redirect_to games_url }
        format.json { head :ok }
      end
    else
      redirect_to root_path
    end
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :release %><br />
    <%= f.text_field :release %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :rating %><br />
    <%= f.text_field :rating %>
  </div>
  <div class="field">
    <%= f.label :total_ratings %><br />
    <%= f.text_field :total_ratings %>
  </div>
  <div class="field">
    <%= f.label :num_ratings %><br />
    <%= f.number_field :num_ratings %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h1>Listing games</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Release</th>
    <th>Image</th>
    <th>Rating</th>
    <th>Total ratings</th>
    <th>Num ratings</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @games.each do |game| %>
  <tr>
    <td><%= game.name %></td>
    <td><%= game.release %></td>
    <td><%= game.image %></td>
    <td><%= game.rating %></td>
    <td><%= game.total_ratings %></td>
    <td><%= game.num_ratings %></td>
    <td><%= link_to 'Show', game %></td>
    <td><%= link_to 'Edit', edit_game_path(game) %></td>
    <td><%= link_to 'Destroy', games_path(:remove => game.id) %> </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @game.name %>
</p>

<p>
  <b>Release:</b>
  <%= @game.release %>
</p>

<p>
  <b>Image:</b>
  <%= @game.image %>
</p>

<p>
  <b>Rating:</b>
  <%= @game.rating %>
</p>

<p>
  <b>Total ratings:</b>
  <%= @game.total_ratings %>
</p>

<p>
  <b>Num ratings:</b>
  <%= @game.num_ratings %>
</p>


<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>