config/routes.rb
BJWlab8::Application.routes.draw do
  resources :games
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :friends, :only => [:new, :create, :destroy]
  resources :collections, :only => [:new, :create, :destroy]

  root :to => 'pages#home'
  match '/home', :to => 'pages#home'
  match '/controlpanel', :to => 'pages#cpanel'
  match '/search', :to => 'pages#gamesearch'
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/collections', :to => 'pages#collections'
  match '/friends', :to => 'pages#friends'
  match '/gpage', :to => 'pages#gpage'
  
  

end

app/views/layouts/_footer.html.erb
<div id="footer">Footer/CR info, etc.</div>

app/views/layouts/_header.html.erb
<div id="banner">
   <%= link_to image_tag("logo.png", :id => "logo", :alt => "Missing Logo"), :root %>
   <div id="users"><%= link_to "Users", '/users' %></div>
   <div id="search">
   <%= form_tag("/search", :method => "get") do %>
     <%= text_field_tag(:q) %>
     <%= submit_tag("Search") %>
   <% end %>
   </div>
   <div id="login">
   	  <%=
   	  if current_user.nil?
   	  	link_to "Register", signup_path
   	  else
   	  	link_to "Control Panel", controlpanel_path
   	  end
   	  %>
      <%=
      if current_user.nil?
      	link_to "Sign In", signin_path
      else
        link_to "Sign Out", signout_path
      end
      %>
   </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title %></title>
  <%= stylesheet_link_tag 'BJWlab7.css', :media => 'screen' %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div id="inner">
	<%= yield %>
	</div>
    <%= render 'layouts/footer' %>
</body>
</html>